### PR TITLE
hammerhead: Unmatched lock in bluetooth_set_power

### LINKED ISSUE #304: WLAN service/cell network service crashes and demands 100% cpu load after booting
- Device: Nexus 5 (Model LG-D821, FCC ID: ZNFD821)
- Channel: Stable Channel
- Build: Ubuntu 15.04 (r2)

## Steps to reproduce

1. Switch on phone: WLAN might be crashed, even also cell phone network (no cell phone network seen), flight mode does not work either -> switch off to reboot
OR
swtich on phone after having it charged over night

## Expected behavoir

Phone boots normally, incorrect 1970 date (see other known bug for hammerhead) is swiftly swichted to correct date, mobile network and WIFI working, phone not getting warm

## Actual behavior

1. Google logo seen for unusal long time
2. Ubports loading screen, App Scope loading, fetching correct date etc. takes all unusal long
3. WIFI not working (service not started)
4. Phone gets warm with 100% cpu load, phone hardly usable, doesn't even shut down properly often (shut down then forced via recovery mode)
5. after about 5 attempts to boot the phone, at one time the phone won't be a hand warmer anymore, cpu is not at 100%, cell phone network and wifi connects normally

## Logfiles and additional information

Screenshot 1: cell phone network and wifi crashed during stand by -> cell phone settings not seen neither in top bar nor in settings, flight mode not working
screenshot20171019_102759160
Screenshot 2: top shows 100% cpu load caused by the process 'wlan_event_handle', note that time/date did not automatically switch from wrong '1970' date
screenshot19700128_230631101

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
This should fix https://github.com/ubports/ubuntu-touch/issues/304 and unblock https://github.com/ubports/lxc-android-config/pull/26 by fixing a one-sided lock causing a race condition.

Change-Id: I1b3cf8094f79b16f7944e28f0670bdbc146a89d6

### CODE REVIEW

File: arch/arm/mach-msm/lge/board-8974-rfkill.c [hunk 1]
```diff
@@ -190,6 +190,9 @@ static int bluetooth_set_power(void *data, bool blocked)
 		gpio_direction_output(GPIO_BT_RESET_N, 0);
 		printk(KERN_ERR "Bluetooth RESET LOW!!");
 	}
+#ifdef CONFIG_BCM4335BT
```
Comment (peat-psuwit) [inline arch/arm/mach-msm/lge/board-8974-rfkill.c:194]: Add a new line before this. Just for readability.

**Review by peat-psuwit — CHANGES_REQUESTED** [review]
Now, I'm not sure if there's anything on Android that might unlock this. I don't think there's any, so leave it in for now. We might get more insight on this when we upstream this to LOS.

Also, a cosmetic change for readability.

File: arch/arm/mach-msm/lge/board-8974-rfkill.c (hunk 1 above)
Comment (UniversalSuperBox) [reply arch/arm/mach-msm/lge/board-8974-rfkill.c:194]: Done!

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Review by peat-psuwit — APPROVED** [review]
Should be good now and suitable for upstream.
